# Desktop workflow stuff

[core]
programs = [
	"hyprland",
	"xdg-desktop-portal-hyprland",
	"obs-studio",
	"waybar",
	"swaylock-effects",
	"swaybg",
	"wofi",
	"cava",
	"foot",
	"mako",
	"feh",
	"brightnessctl"
]
