# Desktop workflow stuff

[core]
programs = [
	"hyprland",
	"xdg-desktop-portal-hyprland",
	"obs-studio",
	"waybar-cava",
	"swaylock-effects",
	"swaybg",
	"wofi",
	"cava",
	"foot",
	"mako",
	"mpv",
	"feh",
	"ncmpcpp",
	"mpd",
	"yt-dlp",
	"brightnessctl",
	"swaync"
]
