[home]
shell = "zsh"
oh_my_zsh = true
env = [
	"GDK_BACKEND=wayland",
	"GTK_THEME=Adwaita-dark",
	"PATH=/home/tray/.nimble/bin/:$PATH"
]
rc = """
export PATH="/home/tray/.nimble/bin/:$PATH"
ZSH_THEME="robbyrussell"
plugins=(git)
"""
