[core]
name = "Example Config"
authors = "xTrayambak"

[distro]
name = "Fedora Linux"
package_sync_repos = "dnf upgrade -y"
package_install_cmd = "dnf install -y"
package_uninstall_cmd = "dnf remove -y"

[user]
name = "tray"
default_password = "districity"
groups = ["wheel", "kvm", "audio", "input"]
