[core]
programs = [
	"zsh",
	"clang",
	"cloc",
	"flatpak",
	"github-cli-git",
	"wl-clipboard",
	"btop"
]

imports = [
	"programming_languages.toml", 
	"desktop.toml", 
	"fonts.toml", 
	"arduino_tools.toml",
	"apps.toml",
	"games.toml",
	"system-packages.toml",
	"editors.toml"
]
